name: Ejecutar Notebook de HubSpot (Semanal)

on:
  # --- SECCIÓN DE CALENDARIO ACTIVADA ---
  schedule:
    # Se ejecuta todos los lunes a las 11:00 AM UTC (7:00 AM en Chile)
    # Formato: Minuto Hora DíaMes Mes DíaSemana
    - cron: '0 11 * * 1'

  # Esta línea te permite seguir ejecutándolo manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias y kernel
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ipykernel
          python -m ipykernel install --user --name=python3

      - name: Ejecutar el notebook
        env:
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
        run: |
          papermill "Actualizar_celular_Hubspot.ipynb" "output.ipynb"
      
      - name: Mostrar el log generado
        if: always() # Se ejecuta incluso si el paso anterior falla
        run: |
          echo "--- Contenido del archivo log.txt ---"
          cat log.txt
          echo "--- Fin del archivo log.txt ---"
